---
# tasks file for ubuntu-bionic

# Copyright (C) 2020 Michael Joseph Walsh - All Rights Reserved
# You may use, distribute and modify this code under the
# terms of the the license.
#
# You should have received a copy of the license with
# this file. If not, please email <mjwalsh@nemonik.com>

- name: upgrade all packages, if Ubuntu-bionic
  become: yes
  apt:
    upgrade: dist
  retries: "{{ default_retries }}"
  delay: "{{ default_delay }}"
  register: result
  until: result is succeeded
  tags:
    - common

- name: ensure development related packages are installed, if Ubuntu-bionic
  become: yes
  apt:
    name: ['util-linux', 'perl', 'sudo', 'tar', 'unzip', 'gzip', 'wget', 'lynx', 'nano', 'vim', 'emacs', 'bash-completion', 'git', 'python', 'python-pip']
  retries: "{{ default_retries }}"
  delay: "{{ default_delay }}"
  register: result
  until: result is succeeded
  tags:
    - common
