galaxy_info:
  author: Michael Joseph Walsh <walsh@nemonik.com>
  description: Ansible role to build and push a standalone-chrome container image into the private registry
  license: 3-Clause BSD License
  min_ansible_version: 2.4
  platforms:
  - name: CentOS
    versions:
    - 7
  galaxy_tags:
  - standalone-chrome-container-image
  - selenium

dependencies: []