galaxy_info:
  author: Michael Joseph Walsh <walsh@nemonik.com>
  description: Ansible role to build an owasp-zap2docker-stable image and push into the private registry 
  license: 3-Clause BSD License
  min_ansible_version: 2.4
  platforms:
  - name: CentOS
    versions:
    - 7
  galaxy_tags:
  - owasp-zap2docker-stable-image

dependencies: []