galaxy_info:
  author: Michael Joseph Walsh <walsh@nemonik.com>
  description: Ansible role used to cache installation content
  license: 3-Clause BSD License
  min_ansible_version: 2.4
  platforms:
  - name: CentOS
    versions:
    - 7
  - name: Alpine
    versions:
    - 3.10
  - name: Ubuntu
    versions:
    - 18.04
  galaxy_tags:
  - create-cache

dependencies: {}
