---
# tasks file for docker

# Copyright (C) 2020 Michael Joseph Walsh - All Rights Reserved
# You may use, distribute and modify this code under the
# terms of the the license.
#
# You should have received a copy of the license with
# this file. If not, please email <mjwalsh@nemonik.com>


# following https://docs.docker.com/install/linux/docker-ce/ubuntu/
- name: ensure the latest version of Docker CE is installed, if Ubuntu-bionic
  block:
  - name: rm docker, docker-engine docker.io
    become: yes
    apt:
      name: [ 'docker', 'docker-engine', 'docker.io', "containerd", "runc" ]
      state: absent
    retries: "{{ default_retries }}"
    delay: "{{ default_delay }}"
    register: result
    until: result is succeeded

  - name: install packages to allow apt to use a repository over HTTPS
    become: yes
    apt:
      name: [ "apt-transport-https", "ca-certificates", "curl", "gnupg-agent", "software-properties-common"] 
      state: latest
      update_cache: yes
    retries: "{{ default_retries }}"
    delay: "{{ default_delay }}"
    register: result
    until: result is succeeded

  - name: add Dockerâ€™s official GPG key
    become: yes
    apt_key:
      keyserver: https://download.docker.com/linux/ubuntu/gpg
      id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
      state: present
    retries: "{{ default_retries }}"
    delay: "{{ default_delay }}"
    register: result
    until: result is succeeded

  - name: add docker repository
    become: yes
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: install latest version of Docker Engine - Community and containerd
    become: yes
    apt:
      name: [ "docker-ce", "docker-ce-cli", "containerd.io" ]
      state: latest
      update_cache: yes
    retries: "{{ default_retries }}"
    delay: "{{ default_delay }}"
    register: result
    until: result is succeeded
  tags:
    - docker
