galaxy_info:
  author: Michael Joseph Walsh <walsh@nemonik.com>
  description: Ansible role to configure a K3s agent
  license: 3-Clause BSD License
  min_ansible_version: 2.4
  platforms:
  - name: CentOS
    versions:
    - 7
  galaxy_tags:
  - k3s-agent
  - kubernetes

dependencies: []