---
# tasks file for sonarqube

# Copyright (C) 2019 Michael Joseph Walsh - All Rights Reserved
# You may use, distribute and modify this code under the
# terms of the the license.
#
# You should have received a copy of the license with
# this file. If not, please email <mjwalsh@nemonik.com>

- name: "create /home/{{ ansible_user_id }}/sonarqube"
  become: yes
  file:
    path: "/home/{{ ansible_user_id }}/sonarqube"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  tags:
    - sonarqube

- name: "template files into /home/{{ ansible_user_id }}/sonarqube"
  become: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "u=rwx,g=r,o=r"  
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    force: yes
  with_items:
    - { src: "templates/README.j2", dest: "/home/{{ ansible_user_id }}/sonarqube/README.MD" }
    - { src: "templates/docker-compose.j2", dest: "/home/{{ ansible_user_id }}/sonarqube/docker-compose.yml" }
    - { src: "templates/Dockerfile.j2", dest: "/home/{{ ansible_user_id }}/sonarqube/Dockerfile" }
    - { src: "templates/dockerfile_build.j2", dest: "/home/{{ ansible_user_id }}/sonarqube/dockerfile_build.sh" }
  tags:
    - sonarqube

- name: "make /home/{{ ansible_user_id }}/sonarqube/dockerfile_build.sh executable"
  become: yes
  file: 
    path: /home/{{ ansible_user_id }}/sonarqube/dockerfile_build.sh
    mode: "u=rwx,g=r,o=r"  
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  tags:
    - sonarqube

- name: "create /home/{{ ansible_user_id }}/sonarqube/volumes/sonarqube-extensions/plugins/ if it doesn't exist"
  become: yes
  file:
    path: /home/{{ ansible_user_id }}/sonarqube/volumes/sonarqube-extensions/plugins/
    state: directory
  tags:
    - sonarqube
 
- name: "build nemonik/sonarqube:{{ sonarqube_version }} docker image"
  become: yes
  docker_image:
    path: "/home/{{ ansible_user_id }}/sonarqube"
    name: "nemonik/sonarqube:{{ sonarqube_version }}"
    buildargs:
      http_proxy: "{{ http_proxy }}"
      HTTP_PROXY: "{{ http_proxy }}"
      https_proxy: "{{ https_proxy }}"
      HTTPS_PROXY: "{{ https_proxy }}"
      NO_PROXY: "{{ no_proxy }}"
      no_proxy: "{{ no_proxy }}" 
  tags:
    - sonarqube
    
- name: spin up sonarqube via docker-compose
  become: yes
  docker_service:
    build: no
    debug: yes
    project_src: "/home/{{ ansible_user_id }}/sonarqube/"
  tags:
    - sonarqube