---
# tasks file for sonar-scanner-cli

# Copyright (C) 2018 Michael Joseph Walsh - All Rights Reserved
# You may use, distribute and modify this code under the
# terms of the the license.
#
# You should have received a copy of the license with
# this file. If not, please email <mjwalsh@nemonik.com>

- name: is sonar-scanner installed?
  stat: 
    path: "/usr/local/sonar-scanner-cli-{{ sonar_scanner_cli_version }}-linux"
  register: sonar_scanner_installed
  tags:
    - sonar-scanner

- name: download and install sonar-scanner binary release
  become: yes
  block:
    - command: /bin/bash -c "wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-{{ sonar_scanner_cli_version }}-linux.zip"
      args:
        chdir: /tmp
    - unarchive:
        src: "/tmp/sonar-scanner-cli-{{ sonar_scanner_cli_version }}-linux.zip"
        dest: /usr/local/
  when: sonar_scanner_installed.stat.exists == False 
  tags:
    - sonar-scanner

- name: ensure /etc/profile.d/path.sh exists
  become: yes   
  file:
    path: /etc/profile.d/devops_class.sh
    state: touch
    mode: 0644

- name: "ensure /etc/profile.d/devops_class.sh PATH includes /usr/local/sonar-scanner-{{ sonar_scanner_cli_version }}-linux/bin"
  become: yes
  block:
    - lineinfile:
        dest: /etc/profile.d/devops_class.sh
        regexp: "^export PATH=$PATH:/usr/local/sonar-scanner-{{ sonar_scanner_cli_version }}-linux/bin"
        state: absent

    - lineinfile:
        dest: /etc/profile.d/devops_class.sh
        line: "export PATH=$PATH:/usr/local/sonar-scanner-{{ sonar_scanner_cli_version }}-linux/bin"
        insertafter: EOF
  tags:
    - sonar-scanner

- name: "ensure the global settings point to the {{ hostvars['toolchain']['ansible_host'] }} hosted SonarQube server"
  become: yes
  lineinfile:
    path: /usr/local/sonar-scanner-{{ sonar_scanner_cli_version }}-linux/conf/sonar-scanner.properties
    regexp: "^#sonar.host.url=http://localhost:9000"
    line: "sonar.host.url=http://{{ hostvars['toolchain']['ansible_host'] }}:9000"
  tags:
    - sonar-scanner
