---
# tasks file for inspec-container-image

# Copyright (C) 2018 Michael Joseph Walsh - All Rights Reserved
# You may use, distribute and modify this code under the
# terms of the the license.
#
# You should have received a copy of the license with
# this file. If not, please email <mjwalsh@nemonik.com>

- name: "create /home/{{ ansible_user_id }}/inspec-container-image"
  become: yes
  file:
    path: "/home/{{ ansible_user_id }}/inspec-container-image"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  tags:    
    - inspec-container-image

- name: "template files into /home/{{ ansible_user_id }}/inspec-container-image"
  become: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}" 
    force: yes  
  with_items:
    - { src: "templates/Dockerfile.j2", dest: "/home/{{ ansible_user_id }}/inspec-container-image/Dockerfile" }
    - { src: "templates/dockerfile_build.j2", dest: "/home/{{ ansible_user_id }}/inspec-container-image/dockerfile_build.sh" }
    - { src: "templates/push_into_private_repo.j2", dest: "/home/{{ ansible_user_id }}/inspec-container-image/push_into_private_repo.sh" }
  tags:    
    - inspec-container-image

- name: "make scripts executable"
  become: yes
  file: 
    path: "{{ item.path }}"
    mode: "u=rwx,g=r,o=r"
  with_items:
    - { path: "/home/{{ ansible_user_id }}/inspec-container-image/push_into_private_repo.sh" }
    - { path: "/home/{{ ansible_user_id }}/inspec-container-image/dockerfile_build.sh" }
  tags:    
    - inspec-container-image

- name: build inspec image and push into private registry
  become: yes
  docker_image:
    path: /home/{{ ansible_user_id }}/inspec-container-image
    name: nemonik/inspec
    repository: "{{ hostvars['toolchain']['ansible_host'] }}:5000/nemonik/inspec"
    push: yes
    tag: "{{ inspec_version }}"
    buildargs:
      http_proxy: "{{ http_proxy }}"
      HTTP_PROXY: "{{ http_proxy }}"
      https_proxy: "{{ https_proxy }}"
      HTTPS_PROXY: "{{ https_proxy }}"
      NO_PROXY: "{{ no_proxy }}"
      no_proxy: "{{ no_proxy }}" 
  tags:    
    - inspec-container-image